package es.ing.icenterprise.arthur.core.domain.model;

import java.util.List;

/**
 * Represents the mapping between an Excel column and a database column.
 * Supports three types:
 *   - Normal: direct Excel → DB mapping
 *   - Auto-generated: TIMESTAMP, UUID (no Excel column needed)
 *   - Concatenated: multiple Excel columns joined into one DB column
 *
 * @param excelColumn  original Excel header name (null for auto-generated/concatenated)
 * @param dbColumn     target database column name
 * @param autoGenerate type of auto-generation: "TIMESTAMP", "UUID" (null if not auto-generated)
 * @param concatenate  list of Excel columns to concatenate (null if not concatenated)
 * @param separator    separator for concatenation (default: empty string)
 */
public record DatabaseMapping(
        String excelColumn,
        String dbColumn,
        String autoGenerate,
        List<String> concatenate,
        String separator
) {

    public DatabaseMapping {
        if (separator == null) separator = "";
    }

    /**
     * Convenience constructor for normal Excel→DB mapping.
     */
    public DatabaseMapping(String excelColumn, String dbColumn) {
        this(excelColumn, dbColumn, null, null, "");
    }

    public boolean isAutoGenerated() {
        return autoGenerate != null && !autoGenerate.isBlank();
    }

    public boolean isConcatenated() {
        return concatenate != null && !concatenate.isEmpty();
    }

    public boolean isNormalField() {
        return !isAutoGenerated() && !isConcatenated();
    }
}
