package es.ing.icenterprise.arthur.adapters.outbound.persistence;

import es.ing.icenterprise.arthur.core.domain.model.Action;
import es.ing.icenterprise.arthur.core.domain.model.DatabaseMapping;
import es.ing.icenterprise.arthur.core.ports.outbound.PersistencePort;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;

import java.sql.Timestamp;
import java.time.LocalDate;
import java.util.*;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.stream.Collectors;

@Component
public class JdbcPersistenceAdapter implements PersistencePort {

    private static final Logger log = LoggerFactory.getLogger(JdbcPersistenceAdapter.class);

    private final JdbcTemplate jdbcTemplate;

    public JdbcPersistenceAdapter(JdbcTemplate jdbcTemplate) {
        this.jdbcTemplate = jdbcTemplate;
    }

    @Override
    public void insertData(List<Action> data, List<DatabaseMapping> mappings, Map<String, Object> parameters) {
        String tableName = (String) parameters.getOrDefault("tableName", "ingesta_data");
        log.info("Inserting {} records into table: {} using {} mappings", data.size(), tableName, mappings.size());

        if (data.isEmpty() || mappings.isEmpty()) return;

        // Build column list from mappings
        List<String> dbColumns = mappings.stream()
                .map(DatabaseMapping::dbColumn)
                .toList();

        // Build placeholders: ? for normal/concat, function call for auto-generated
        List<String> placeholders = mappings.stream()
                .map(this::buildPlaceholder)
                .toList();

        String sql = String.format("INSERT INTO %s (%s) VALUES (%s)",
                tableName,
                String.join(", ", dbColumns),
                String.join(", ", placeholders));

        log.debug("Generated SQL: {}", sql);

        // Resolve ingest date: from filename (passed via params) or fallback to today
        LocalDate ingestDate = (LocalDate) parameters.getOrDefault("_ingestDate", LocalDate.now());
        Timestamp ingestTimestamp = Timestamp.valueOf(ingestDate.atStartOfDay());

        List<Object[]> batchArgs = data.stream()
                .map(action -> buildRowArgs(action, mappings, ingestTimestamp))
                .toList();

        jdbcTemplate.batchUpdate(sql, batchArgs);
        log.info("Successfully inserted {} records into {}", data.size(), tableName);
    }

    @Override
    public Object check(Object data, Map<String, Object> parameters) {
        String query = (String) parameters.getOrDefault("query", "SELECT 1");
        log.info("Executing check query: {}", query);
        return jdbcTemplate.queryForObject(query, Object.class);
    }

    @Override
    public void truncate(Map<String, Object> parameters) {
        String tableName = (String) parameters.getOrDefault("tableName", "ingesta_data");
        String timestampColumn = (String) parameters.get("timestampColumn");

        if (timestampColumn != null) {
            LocalDate ingestDate = (LocalDate) parameters.getOrDefault("_ingestDate", LocalDate.now());
            Timestamp today = Timestamp.valueOf(ingestDate.atStartOfDay());
            log.info("Deleting records from {} where {} = {}", tableName, timestampColumn, today);
            int deleted = jdbcTemplate.update(
                    "DELETE FROM " + tableName + " WHERE " + timestampColumn + " = ?", today);
            log.info("Deleted {} records from {}", deleted, tableName);
        } else {
            log.info("Truncating table: {}", tableName);
            jdbcTemplate.execute("TRUNCATE TABLE " + tableName);
        }
    }

    /**
     * Builds the placeholder for a mapping in the VALUES clause.
     * Normal and concatenated fields use ?, auto-generated use ? too
     * (we resolve values in Java, not DB functions, for portability).
     */
    private String buildPlaceholder(DatabaseMapping mapping) {
        return "?";
    }

    /**
     * Builds the argument array for a single row based on the mappings.
     */
    private Object[] buildRowArgs(Action action, List<DatabaseMapping> mappings, Timestamp ingestTimestamp) {
        return mappings.stream()
                .map(mapping -> resolveValue(action, mapping, ingestTimestamp))
                .toArray();
    }

    /**
     * Resolves the value for a single mapping from an Action row.
     */
    private Object resolveValue(Action action, DatabaseMapping mapping, Timestamp ingestTimestamp) {
        if (mapping.isAutoGenerated()) {
            return resolveAutoGenerated(mapping, ingestTimestamp);
        }

        if (mapping.isConcatenated()) {
            return resolveConcatenated(action, mapping);
        }

        // Normal mapping: get value from Excel by original header name
        return action.get(mapping.excelColumn());
    }

    private Object resolveAutoGenerated(DatabaseMapping mapping, Timestamp ingestTimestamp) {
        return switch (mapping.autoGenerate().toUpperCase()) {
            case "TIMESTAMP" -> ingestTimestamp;
            case "UUID" -> UUID.randomUUID().toString();
            default -> {
                log.warn("Unknown autoGenerate type: {}", mapping.autoGenerate());
                yield null;
            }
        };
    }

    @Override
    public boolean checkExists(String tableName, String schema, String idColumn, Object idValue,
                               String timestampColumn, LocalDate date) {
        String fullTable = schema != null ? schema + "." + tableName : tableName;
        String sql = "SELECT COUNT(*) FROM " + fullTable
                + " WHERE " + idColumn + " = ? AND " + timestampColumn + " = ?";
        Timestamp ts = Timestamp.valueOf(date.atStartOfDay());
        Integer count = jdbcTemplate.queryForObject(sql, Integer.class, idValue, ts);
        return count != null && count > 0;
    }

    @Override
    public void insertRow(String tableName, String schema, Map<String, Object> columnValues) {
        String fullTable = schema != null ? schema + "." + tableName : tableName;
        List<String> columns = new ArrayList<>(columnValues.keySet());
        String placeholders = columns.stream().map(c -> "?").collect(Collectors.joining(", "));
        String sql = "INSERT INTO " + fullTable + " (" + String.join(", ", columns) + ") VALUES (" + placeholders + ")";

        Object[] args = columns.stream()
                .map(col -> {
                    Object v = columnValues.get(col);
                    return v instanceof LocalDate ld ? Timestamp.valueOf(ld.atStartOfDay()) : v;
                })
                .toArray();

        jdbcTemplate.update(sql, args);
        log.debug("Inserted row into {}: {}", fullTable, columnValues);
    }

    @Override
    public Set<Object> loadReferenceIds(String tableName, String schema, String idColumn,
                                        String timestampColumn, LocalDate date) {
        String fullTable = schema != null ? schema + "." + tableName : tableName;
        String sql = "SELECT " + idColumn + " FROM " + fullTable + " WHERE " + timestampColumn + " = ?";
        Timestamp ts = Timestamp.valueOf(date.atStartOfDay());
        List<Object> ids = jdbcTemplate.queryForList(sql, Object.class, ts);
        return new HashSet<>(ids);
    }

    @Override
    public Set<Object> loadExistingIds(String tableName, String schema, String idColumn) {
        String fullTable = schema != null ? schema + "." + tableName : tableName;
        String sql = "SELECT " + idColumn + " FROM " + fullTable;
        List<Object> ids = jdbcTemplate.queryForList(sql, Object.class);
        return new HashSet<>(ids);
    }

    private Object resolveConcatenated(Action action, DatabaseMapping mapping) {
        return mapping.concatenate().stream()
                .map(col -> {
                    Object val = action.get(col);
                    return val != null ? val.toString() : "";
                })
                .filter(s -> !s.isBlank())
                .collect(Collectors.joining(mapping.separator()));
    }
}
