package es.ing.icenterprise.arthur.adapters.outbound.persistence;

import es.ing.icenterprise.arthur.core.domain.model.Action;
import es.ing.icenterprise.arthur.core.domain.model.DatabaseMapping;
import es.ing.icenterprise.arthur.core.ports.outbound.InsertResult;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.JdbcTest;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.transaction.PlatformTransactionManager;
import org.springframework.transaction.TransactionDefinition;
import org.springframework.transaction.support.TransactionTemplate;

import java.time.LocalDate;
import java.util.List;
import java.util.Map;
import java.util.Set;

import static org.assertj.core.api.Assertions.assertThat;

@JdbcTest
class JdbcPersistenceAdapterTest {

    @Autowired
    JdbcTemplate jdbcTemplate;

    @Autowired
    PlatformTransactionManager txManager;

    private JdbcPersistenceAdapter adapter;
    private TransactionTemplate committedTx;

    @BeforeEach
    void setUp() {
        adapter = new JdbcPersistenceAdapter(jdbcTemplate, txManager);
        committedTx = new TransactionTemplate(txManager);
        committedTx.setPropagationBehavior(TransactionDefinition.PROPAGATION_REQUIRES_NEW);

        jdbcTemplate.execute(
                "CREATE TABLE IF NOT EXISTS ITEMS (ID VARCHAR(50), NAME VARCHAR(100), TS TIMESTAMP, SCORE DOUBLE)");
        jdbcTemplate.execute(
                "CREATE TABLE IF NOT EXISTS LOOKUP_TABLE (KEY_COL VARCHAR(50), VAL_COL VARCHAR(100), TS TIMESTAMP)");
        jdbcTemplate.execute(
                "CREATE TABLE IF NOT EXISTS BISECT_ITEMS (ID VARCHAR(50) PRIMARY KEY, NAME VARCHAR(100))");
        jdbcTemplate.execute("DELETE FROM ITEMS");
        jdbcTemplate.execute("DELETE FROM LOOKUP_TABLE");
        // BISECT_ITEMS is written via REQUIRES_NEW (the adapter's bisect),
        // which commits independently of @JdbcTest's rollback. Clean it with
        // its own committed transaction so state does not leak across tests.
        committedTx.executeWithoutResult(s -> jdbcTemplate.execute("DELETE FROM BISECT_ITEMS"));
    }

    // ── insertData ────────────────────────────────────────────────────────────

    @Test
    @DisplayName("insertData inserts rows using normal column mappings")
    void insertDataInsertsNormalMappings() {
        Action row = new Action(Map.of("Name", "Alice"));
        DatabaseMapping mapping = new DatabaseMapping("Name", "NAME");

        adapter.insertData(
                List.of(row),
                List.of(mapping),
                Map.of("tableName", "ITEMS", "_ingestDate", LocalDate.of(2026, 1, 1)));

        Integer count = jdbcTemplate.queryForObject("SELECT COUNT(*) FROM ITEMS WHERE NAME='Alice'", Integer.class);
        assertThat(count).isEqualTo(1);
    }

    @Test
    @DisplayName("insertData with auto-generated TIMESTAMP column fills TS column")
    void insertDataAutoGeneratedTimestamp() {
        DatabaseMapping tsMapping = new DatabaseMapping(null, "TS", "TIMESTAMP", null, null);
        DatabaseMapping nameMapping = new DatabaseMapping("Name", "NAME");

        Action row = new Action(Map.of("Name", "Bob"));
        adapter.insertData(
                List.of(row),
                List.of(nameMapping, tsMapping),
                Map.of("tableName", "ITEMS", "_ingestDate", LocalDate.of(2026, 3, 15)));

        Integer count = jdbcTemplate.queryForObject(
                "SELECT COUNT(*) FROM ITEMS WHERE NAME='Bob' AND TS IS NOT NULL", Integer.class);
        assertThat(count).isEqualTo(1);
    }

    @Test
    @DisplayName("insertData with auto-generated UUID column fills ID column")
    void insertDataAutoGeneratedUuid() {
        DatabaseMapping uuidMapping = new DatabaseMapping(null, "ID", "UUID", null, null);
        DatabaseMapping nameMapping = new DatabaseMapping("Name", "NAME");

        Action row = new Action(Map.of("Name", "Carol"));
        adapter.insertData(
                List.of(row),
                List.of(nameMapping, uuidMapping),
                Map.of("tableName", "ITEMS", "_ingestDate", LocalDate.of(2026, 3, 15)));

        String id = jdbcTemplate.queryForObject(
                "SELECT ID FROM ITEMS WHERE NAME='Carol'", String.class);
        assertThat(id).isNotBlank().hasSize(36); // UUID format
    }

    @Test
    @DisplayName("insertData with concatenated mapping joins columns with separator")
    void insertDataConcatenatedMapping() {
        DatabaseMapping concatMapping = new DatabaseMapping(null, "NAME", null, List.of("First", "Last"), "-");

        Action row = new Action(Map.of("First", "John", "Last", "Doe"));
        adapter.insertData(
                List.of(row),
                List.of(concatMapping),
                Map.of("tableName", "ITEMS", "_ingestDate", LocalDate.of(2026, 3, 15)));

        String name = jdbcTemplate.queryForObject("SELECT NAME FROM ITEMS", String.class);
        assertThat(name).isEqualTo("John-Doe");
    }

    @Test
    @DisplayName("insertData does nothing when data list is empty")
    void insertDataEmptyListDoesNothing() {
        adapter.insertData(List.of(), List.of(new DatabaseMapping("Name", "NAME")),
                Map.of("tableName", "ITEMS"));
        Integer count = jdbcTemplate.queryForObject("SELECT COUNT(*) FROM ITEMS", Integer.class);
        assertThat(count).isZero();
    }

    @Test
    @DisplayName("insertData does nothing when mapping list is empty")
    void insertDataEmptyMappingsDoesNothing() {
        adapter.insertData(List.of(new Action(Map.of("Name", "X"))), List.of(),
                Map.of("tableName", "ITEMS"));
        Integer count = jdbcTemplate.queryForObject("SELECT COUNT(*) FROM ITEMS", Integer.class);
        assertThat(count).isZero();
    }

    @Test
    @DisplayName("insertData returns inserted count when the whole batch succeeds")
    void insertDataReturnsInsertedCountOnSuccess() {
        List<Action> rows = List.of(
                new Action(Map.of("ID", "a", "Name", "Alice")),
                new Action(Map.of("ID", "b", "Name", "Bob")),
                new Action(Map.of("ID", "c", "Name", "Carol")));
        List<DatabaseMapping> mappings = List.of(
                new DatabaseMapping("ID", "ID"),
                new DatabaseMapping("Name", "NAME"));

        InsertResult result = adapter.insertData(rows, mappings,
                Map.of("tableName", "BISECT_ITEMS", "_ingestDate", LocalDate.of(2026, 1, 1)));

        assertThat(result.inserted()).isEqualTo(3);
        assertThat(result.failed()).isZero();
        List<String> ids = jdbcTemplate.queryForList(
                "SELECT ID FROM BISECT_ITEMS ORDER BY ID", String.class);
        assertThat(ids).containsExactly("a", "b", "c");
    }

    @Test
    @DisplayName("insertData bisects on constraint violation, persisting good rows only")
    void insertDataBisectsOnConstraintViolation() {
        // Pre-insert 'dup' in a committed tx so the adapter's REQUIRES_NEW sees it.
        committedTx.executeWithoutResult(s ->
                jdbcTemplate.update("INSERT INTO BISECT_ITEMS (ID, NAME) VALUES ('dup', 'pre')"));

        List<Action> rows = List.of(
                new Action(Map.of("ID", "a", "Name", "Alice")),
                new Action(Map.of("ID", "dup", "Name", "Duplicate")),
                new Action(Map.of("ID", "c", "Name", "Carol")),
                new Action(Map.of("ID", "d", "Name", "Dave")));
        List<DatabaseMapping> mappings = List.of(
                new DatabaseMapping("ID", "ID"),
                new DatabaseMapping("Name", "NAME"));

        InsertResult result = adapter.insertData(rows, mappings,
                Map.of("tableName", "BISECT_ITEMS", "_ingestDate", LocalDate.of(2026, 1, 1)));

        assertThat(result.inserted()).isEqualTo(3);
        assertThat(result.failed()).isEqualTo(1);
        List<String> ids = jdbcTemplate.queryForList(
                "SELECT ID FROM BISECT_ITEMS ORDER BY ID", String.class);
        assertThat(ids).containsExactly("a", "c", "d", "dup");
    }

    @Test
    @DisplayName("insertData isolates multiple bad rows independently")
    void insertDataBisectsMultipleBadRows() {
        committedTx.executeWithoutResult(s -> {
            jdbcTemplate.update("INSERT INTO BISECT_ITEMS (ID) VALUES ('x1')");
            jdbcTemplate.update("INSERT INTO BISECT_ITEMS (ID) VALUES ('x2')");
        });

        List<Action> rows = List.of(
                new Action(Map.of("ID", "x1", "Name", "bad-1")),
                new Action(Map.of("ID", "a",  "Name", "good")),
                new Action(Map.of("ID", "x2", "Name", "bad-2")),
                new Action(Map.of("ID", "b",  "Name", "good")));
        List<DatabaseMapping> mappings = List.of(
                new DatabaseMapping("ID", "ID"),
                new DatabaseMapping("Name", "NAME"));

        InsertResult result = adapter.insertData(rows, mappings,
                Map.of("tableName", "BISECT_ITEMS", "_ingestDate", LocalDate.of(2026, 1, 1)));

        assertThat(result.inserted()).isEqualTo(2);
        assertThat(result.failed()).isEqualTo(2);
        List<String> ids = jdbcTemplate.queryForList(
                "SELECT ID FROM BISECT_ITEMS ORDER BY ID", String.class);
        assertThat(ids).containsExactly("a", "b", "x1", "x2");
    }

    @Test
    @DisplayName("insertData returns EMPTY when data list is empty (no bisect attempt)")
    void insertDataReturnsEmptyForEmptyInput() {
        InsertResult result = adapter.insertData(List.of(),
                List.of(new DatabaseMapping("ID", "ID")),
                Map.of("tableName", "BISECT_ITEMS"));
        assertThat(result).isEqualTo(InsertResult.EMPTY);
    }

    // ── check ─────────────────────────────────────────────────────────────────

    @Test
    @DisplayName("check executes arbitrary query and returns result")
    void checkExecutesArbitraryQuery() {
        Object result = adapter.check(null, Map.of("query", "SELECT 42"));
        assertThat(result).isNotNull();
        assertThat(result.toString()).isEqualTo("42");
    }

    // ── truncate ──────────────────────────────────────────────────────────────

    @Test
    @DisplayName("truncate with timestampColumn deletes matching rows only")
    void truncateWithTimestampColumnDeletesMatchingRows() {
        LocalDate date = LocalDate.of(2026, 1, 1);
        jdbcTemplate.update("INSERT INTO ITEMS (ID, TS) VALUES ('r1', ?)",
                java.sql.Timestamp.valueOf(date.atStartOfDay()));
        jdbcTemplate.update("INSERT INTO ITEMS (ID, TS) VALUES ('r2', ?)",
                java.sql.Timestamp.valueOf(LocalDate.of(2025, 1, 1).atStartOfDay()));

        adapter.truncate(Map.of("tableName", "ITEMS", "timestampColumn", "TS", "_ingestDate", date));

        List<String> remaining = jdbcTemplate.queryForList("SELECT ID FROM ITEMS", String.class);
        assertThat(remaining).containsExactly("r2");
    }

    @Test
    @DisplayName("truncate without timestampColumn truncates the whole table")
    void truncateWithoutTimestampColumnTruncatesAll() {
        jdbcTemplate.update("INSERT INTO ITEMS (ID) VALUES ('x')");
        jdbcTemplate.update("INSERT INTO ITEMS (ID) VALUES ('y')");

        adapter.truncate(Map.of("tableName", "ITEMS"));

        Integer count = jdbcTemplate.queryForObject("SELECT COUNT(*) FROM ITEMS", Integer.class);
        assertThat(count).isZero();
    }

    // ── checkExists ───────────────────────────────────────────────────────────

    @Test
    @DisplayName("checkExists returns true when row exists with matching id and date")
    void checkExistsReturnsTrueForMatch() {
        LocalDate date = LocalDate.of(2026, 2, 10);
        jdbcTemplate.update("INSERT INTO ITEMS (ID, TS) VALUES ('abc', ?)",
                java.sql.Timestamp.valueOf(date.atStartOfDay()));

        boolean exists = adapter.checkExists("ITEMS", null, "ID", "abc", "TS", date);
        assertThat(exists).isTrue();
    }

    @Test
    @DisplayName("checkExists returns false when id does not match")
    void checkExistsReturnsFalseForNoMatch() {
        LocalDate date = LocalDate.of(2026, 2, 10);
        jdbcTemplate.update("INSERT INTO ITEMS (ID, TS) VALUES ('abc', ?)",
                java.sql.Timestamp.valueOf(date.atStartOfDay()));

        boolean exists = adapter.checkExists("ITEMS", null, "ID", "other", "TS", date);
        assertThat(exists).isFalse();
    }

    // ── insertRow ─────────────────────────────────────────────────────────────

    @Test
    @DisplayName("insertRow inserts a single row with string values")
    void insertRowInsertsStringValues() {
        adapter.insertRow("ITEMS", null, Map.of("ID", "r1", "NAME", "test"));

        Integer count = jdbcTemplate.queryForObject(
                "SELECT COUNT(*) FROM ITEMS WHERE ID='r1' AND NAME='test'", Integer.class);
        assertThat(count).isEqualTo(1);
    }

    @Test
    @DisplayName("insertRow converts LocalDate values to Timestamp")
    void insertRowConvertsLocalDateToTimestamp() {
        LocalDate date = LocalDate.of(2026, 4, 1);
        adapter.insertRow("ITEMS", null, Map.of("ID", "r2", "TS", date));

        Integer count = jdbcTemplate.queryForObject(
                "SELECT COUNT(*) FROM ITEMS WHERE ID='r2' AND TS IS NOT NULL", Integer.class);
        assertThat(count).isEqualTo(1);
    }

    // ── loadReferenceIds ──────────────────────────────────────────────────────

    @Test
    @DisplayName("loadReferenceIds returns ids for the given timestamp")
    void loadReferenceIdsReturnsMatchingIds() {
        LocalDate date = LocalDate.of(2026, 3, 1);
        java.sql.Timestamp ts = java.sql.Timestamp.valueOf(date.atStartOfDay());
        jdbcTemplate.update("INSERT INTO ITEMS (ID, TS) VALUES ('id1', ?)", ts);
        jdbcTemplate.update("INSERT INTO ITEMS (ID, TS) VALUES ('id2', ?)", ts);
        jdbcTemplate.update("INSERT INTO ITEMS (ID, TS) VALUES ('id3', ?)",
                java.sql.Timestamp.valueOf(LocalDate.of(2025, 1, 1).atStartOfDay()));

        Set<Object> ids = adapter.loadReferenceIds("ITEMS", null, "ID", "TS", date);
        assertThat(ids).containsExactlyInAnyOrder("id1", "id2");
    }

    // ── loadExistingIds ───────────────────────────────────────────────────────

    @Test
    @DisplayName("loadExistingIds returns all ids regardless of timestamp")
    void loadExistingIdsReturnsAll() {
        jdbcTemplate.update("INSERT INTO ITEMS (ID) VALUES ('a')");
        jdbcTemplate.update("INSERT INTO ITEMS (ID) VALUES ('b')");

        Set<Object> ids = adapter.loadExistingIds("ITEMS", null, "ID");
        assertThat(ids).containsExactlyInAnyOrder("a", "b");
    }

    @Test
    @DisplayName("loadExistingIds returns empty set when table is empty")
    void loadExistingIdsEmptyTable() {
        Set<Object> ids = adapter.loadExistingIds("ITEMS", null, "ID");
        assertThat(ids).isEmpty();
    }

    // ── updateData ────────────────────────────────────────────────────────────

    @Test
    @DisplayName("updateData updates non-id columns for matching id")
    void updateDataUpdatesNonIdColumns() {
        jdbcTemplate.update("INSERT INTO ITEMS (ID, NAME) VALUES ('u1', 'old')");

        Action row = new Action(Map.of("ID", "u1", "Name", "new"));
        List<DatabaseMapping> mappings = List.of(
                new DatabaseMapping("ID", "ID"),
                new DatabaseMapping("Name", "NAME"));

        adapter.updateData(List.of(row), mappings,
                Map.of("tableName", "ITEMS", "_ingestDate", LocalDate.of(2026, 1, 1)),
                "ID");

        String name = jdbcTemplate.queryForObject(
                "SELECT NAME FROM ITEMS WHERE ID='u1'", String.class);
        assertThat(name).isEqualTo("new");
    }

    @Test
    @DisplayName("updateData does nothing when data list is empty")
    void updateDataEmptyListDoesNothing() {
        jdbcTemplate.update("INSERT INTO ITEMS (ID, NAME) VALUES ('u1', 'unchanged')");
        adapter.updateData(List.of(), List.of(new DatabaseMapping("ID", "ID")),
                Map.of("tableName", "ITEMS"), "ID");
        String name = jdbcTemplate.queryForObject(
                "SELECT NAME FROM ITEMS WHERE ID='u1'", String.class);
        assertThat(name).isEqualTo("unchanged");
    }

    // ── lookupValues ──────────────────────────────────────────────────────────

    @Test
    @DisplayName("lookupValues without timestampColumn returns all key-value pairs")
    void lookupValuesWithoutTimestampReturnsAll() {
        jdbcTemplate.update("INSERT INTO LOOKUP_TABLE (KEY_COL, VAL_COL) VALUES ('alice@x.com', 'CK001')");
        jdbcTemplate.update("INSERT INTO LOOKUP_TABLE (KEY_COL, VAL_COL) VALUES ('bob@x.com', 'CK002')");

        Map<String, String> result = adapter.lookupValues("LOOKUP_TABLE", null, "KEY_COL", "VAL_COL", null);
        assertThat(result).containsEntry("alice@x.com", "CK001")
                          .containsEntry("bob@x.com", "CK002");
    }

    @Test
    @DisplayName("lookupValues with timestampColumn returns only entries with max timestamp")
    void lookupValuesWithTimestampReturnsMaxTimestampEntries() {
        java.sql.Timestamp older = java.sql.Timestamp.valueOf(LocalDate.of(2025, 1, 1).atStartOfDay());
        java.sql.Timestamp newer = java.sql.Timestamp.valueOf(LocalDate.of(2026, 1, 1).atStartOfDay());
        jdbcTemplate.update("INSERT INTO LOOKUP_TABLE VALUES ('k1', 'old', ?)", older);
        jdbcTemplate.update("INSERT INTO LOOKUP_TABLE VALUES ('k2', 'new', ?)", newer);

        Map<String, String> result = adapter.lookupValues(
                "LOOKUP_TABLE", null, "KEY_COL", "VAL_COL", "TS");
        assertThat(result).containsOnlyKeys("k2")
                          .containsEntry("k2", "new");
    }

    @Test
    @DisplayName("lookupValues keys are lowercased")
    void lookupValuesKeysAreLowercased() {
        jdbcTemplate.update("INSERT INTO LOOKUP_TABLE (KEY_COL, VAL_COL) VALUES ('UPPER@CASE.COM', 'CK99')");

        Map<String, String> result = adapter.lookupValues("LOOKUP_TABLE", null, "KEY_COL", "VAL_COL", null);
        assertThat(result).containsKey("upper@case.com");
    }
}
